[tool.poetry]
name = "hw_tooling"
version = "0.1.0"
description = ""
authors = ["dgronskij <gronsky.dm@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
